[pytest]
filterwarnings =
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
    ignore:torchaudio\._backend\.set_audio_backend has been deprecated.*:UserWarning
    ignore:torchaudio\._backend\.get_audio_backend has been deprecated.*:UserWarning
    ignore:Module 'speechbrain\.pretrained' was deprecated.*:UserWarning
    ignore:.*torchaudio\.backend\.common\.AudioMetaData.*:UserWarning
